language: python
os: linux
dist: focal

python:
  - "3.8"

install:
  - pip install -r requirements.txt

# command to run tests
on:
  - master:  
      script: python3 main.py
  - dev:
      script: python3 dev/lint_all.py